<a href="https://colab.research.google.com/github/mssabahi/Deep_Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook the fundamental of tensors will be used using tensorflow.
More specifically:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.functions (a way to speed of your regular Python function)
* Using GPUs or TPUs with tensorflows
* Excersise to try for yourself

# Introduction to Tensors

In [1]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


# Creating tensors with tf.constant()
As mentioned before, in general, you usually won't create tensors yourself. This is because TensorFlow has modules built-in (such as tf.io and tf.data) which are able to read your data sources and automatically convert them to tensors and then later on, neural network models will process these for us.

In [2]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[2,3],
                      [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
matrix2 = tf.constant([
                       [[2,3,4,5],
                        [6,7,8,9]]
                       ,
                        [[1,2,3,3],
                        [0,1,2,2]]
                       ], dtype=float)
matrix2

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[2., 3., 4., 5.],
        [6., 7., 8., 9.]],

       [[1., 2., 3., 3.],
        [0., 1., 2., 2.]]], dtype=float32)>

In [9]:
matrix2.ndim

3

# Creating with tf.variable

In [10]:
tf.Variable

tensorflow.python.ops.variables.Variable

The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [11]:
# Create the same tensor with tf.Variable() and tf.constant()
changable_tensor = tf.Variable([12,13])
unchangable_tensor = tf.constant([12,14])

In [12]:
changable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [13]:
# changable_tensor[0] = 2

# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# <ipython-input-14-e40dbc510147> in <module>()
# ----> 1 changable_tensor[0] = 2

# TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
changable_tensor[0].assign(2)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 2, 13], dtype=int32)>

In [15]:
# unchangable_tensor[0].assign(2)
# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# <ipython-input-16-a69bfbc2f360> in <module>()
# ----> 1 unchangable_tensor[0].assign(2)

# /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in __getattr__(self, name)
#     399         from tensorflow.python.ops.numpy_ops import np_config
#     400         np_config.enable_numpy_behavior()""".format(type(self).__name__, name))
# --> 401     self.__getattribute__(name)
#     402 
#     403   @staticmethod

# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Rarley in practice we need to decide whether to use tf.constant or tf.Variable

# Creating random tensors
have arbitrary size contain random numbers


In [16]:
rnd_n_1 = tf.random.Generator.from_seed(42 )
rnd_n_1 = rnd_n_1.normal(shape=(4,2))

rnd_u_1 = tf.random.Generator.from_seed(42 )
rnd_u_1 = rnd_u_1.uniform(shape=(4,2))

print(f'Variables with Normal Distribution = {rnd_n_1}')
print(f'Variables with Uniform Distribution = {rnd_u_1}')

Variables with Normal Distribution = [[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]]
Variables with Uniform Distribution = [[0.7493447  0.73561966]
 [0.45230794 0.49039817]
 [0.1889317  0.52027524]
 [0.8736881  0.46921718]]


In [17]:
tf.random.get_global_generator().normal((2,3)) # To generate random number without seeds

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.3558414 ,  0.26764822, -0.72009915],
       [-0.7519263 , -0.6281898 , -0.36892524]], dtype=float32)>

# Shuffling the order of tensors
(valuable for when you want to shuffle your data)

In [18]:
not_shuffled = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
not_shuffled

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [19]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [20]:
# !pip install emath@git+git://github.com/whitead/emoji-math.git

# Creating a tensor from NumPy arrays.

In [21]:
tf.ones((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros((3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

### The main difference between tensors and NumPy arrays is that tensors can be run on GPUs.


🔑 Note: A matrix or tensor is typically represented by a capital letter (e.g. **X** or **A**) where as a vector is typically represented by a lowercase 
letter (e.g. **y** or **b**).



In [23]:
aa = tf.ones((2, 3, 3, 4))
aa

<tf.Tensor: shape=(2, 3, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
tf.Variable(initial_value=[123])

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([123], dtype=int32)>

In [25]:
tf_test_01 = tf.Variable(tf.random.uniform([2,3,2,2], 0, 10, dtype=tf.int32, seed=0))
tf_test_01

<tf.Variable 'Variable:0' shape=(2, 3, 2, 2) dtype=int32, numpy=
array([[[[3, 1],
         [7, 7]],

        [[3, 5],
         [4, 1]],

        [[3, 9],
         [3, 1]]],


       [[[1, 5],
         [7, 1]],

        [[0, 7],
         [3, 9]],

        [[3, 8],
         [0, 5]]]], dtype=int32)>

In [26]:
tf_test_01[1,0,1,1].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3, 2, 2) dtype=int32, numpy=
array([[[[  3,   1],
         [  7,   7]],

        [[  3,   5],
         [  4,   1]],

        [[  3,   9],
         [  3,   1]]],


       [[[  1,   5],
         [  7, 100]],

        [[  0,   7],
         [  3,   9]],

        [[  3,   8],
         [  0,   5]]]], dtype=int32)>

In [27]:
tf_test_01 = tf.random.Generator.from_seed(1234)

tf_test_01 = tf.random.Generator.from_seed(20).normal((2,4,2,3))
tf_test_01

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float32, numpy=
array([[[[ 0.88051325, -1.6833194 ,  0.86754173],
         [-0.19625713, -1.322665  , -0.02279496]],

        [[-0.1383193 ,  0.44207528, -0.7531523 ],
         [ 2.0261486 , -0.06997604,  0.85445154]],

        [[ 0.1175475 ,  0.03493892, -1.5700307 ],
         [ 0.4457582 ,  0.10944034, -0.8035768 ]],

        [[-1.7166729 ,  0.3738578 , -0.14371012],
         [-0.34646833,  1.1456194 , -0.416     ]]],


       [[[ 0.43369916,  1.0241015 , -0.74785167],
         [-0.59090924, -1.2060374 ,  0.8307429 ]],

        [[ 1.0951619 ,  1.3672234 , -0.54532146],
         [ 1.9302735 , -0.3151453 , -0.8761205 ]],

        [[-2.7316678 , -0.15730922,  1.3692921 ],
         [-0.4367834 ,  0.8357487 ,  0.20849545]],

        [[ 1.4040174 , -2.735283  ,  1.2232229 ],
         [-1.8653691 ,  0.00511209, -1.0493753 ]]]], dtype=float32)>

In [28]:
tf_test_01[0,1,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.1383193>

# Getting Information from tensors

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

*   **Shape**: The length (number of elements) of each of the dimensions of a tensor.
*   **Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
*   **Axis** or Dimension: A particular dimension of a tensor.
*   **Size**: The total number of items in the tensor.


In [29]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros((2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])

Elements along axis 0 of tensor: 2


In [31]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


# Indexing
You can also index tensors just like Python lists.



In [32]:
tf.random.set_seed(5)
rank_4_tensor_new = tf.Variable(tf.random.uniform([2,3,4,5]))
rank_4_tensor_new

<tf.Variable 'Variable:0' shape=(2, 3, 4, 5) dtype=float32, numpy=
array([[[[0.6263931 , 0.5298432 , 0.7584572 , 0.5084884 , 0.34415376],
         [0.31959772, 0.69165003, 0.2665254 , 0.03728402, 0.20195806],
         [0.27757192, 0.14514387, 0.2632339 , 0.30723798, 0.3054142 ],
         [0.40084064, 0.31193304, 0.90468144, 0.7916621 , 0.75609195]],

        [[0.6157565 , 0.03640282, 0.93310726, 0.7649263 , 0.7422414 ],
         [0.02858794, 0.34645987, 0.44837487, 0.46826434, 0.93760514],
         [0.49955702, 0.8588258 , 0.56008434, 0.60858595, 0.5712477 ],
         [0.57801986, 0.99914443, 0.5327579 , 0.04764938, 0.3474946 ]],

        [[0.33369792, 0.89474916, 0.9426874 , 0.9472102 , 0.10648286],
         [0.617066  , 0.8403715 , 0.7066246 , 0.59802914, 0.0299114 ],
         [0.0022999 , 0.5984256 , 0.05244112, 0.5965891 , 0.81351566],
         [0.37422216, 0.57518184, 0.3036133 , 0.44588637, 0.513654  ]]],


       [[[0.5504117 , 0.17384589, 0.85631883, 0.8028133 , 0.72859514],
  

In [33]:
# Get the first 2 items of each dimension
rank_4_tensor_new[:6,:66,:6,:6]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.6263931 , 0.5298432 , 0.7584572 , 0.5084884 , 0.34415376],
         [0.31959772, 0.69165003, 0.2665254 , 0.03728402, 0.20195806],
         [0.27757192, 0.14514387, 0.2632339 , 0.30723798, 0.3054142 ],
         [0.40084064, 0.31193304, 0.90468144, 0.7916621 , 0.75609195]],

        [[0.6157565 , 0.03640282, 0.93310726, 0.7649263 , 0.7422414 ],
         [0.02858794, 0.34645987, 0.44837487, 0.46826434, 0.93760514],
         [0.49955702, 0.8588258 , 0.56008434, 0.60858595, 0.5712477 ],
         [0.57801986, 0.99914443, 0.5327579 , 0.04764938, 0.3474946 ]],

        [[0.33369792, 0.89474916, 0.9426874 , 0.9472102 , 0.10648286],
         [0.617066  , 0.8403715 , 0.7066246 , 0.59802914, 0.0299114 ],
         [0.0022999 , 0.5984256 , 0.05244112, 0.5965891 , 0.81351566],
         [0.37422216, 0.57518184, 0.3036133 , 0.44588637, 0.513654  ]]],


       [[[0.5504117 , 0.17384589, 0.85631883, 0.8028133 , 0.72859514],
         [0.331

In [34]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

### You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.

In [35]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_3_tensor
# rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### You can achieve the same using tf.expand_dims().



In [36]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating tensors (tensor operations)


### Basic operations¶

You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as
, `+`, `-`, `*`.

In [37]:
# You can add values to a tensor using the addition operator
ts_01 = tf.constant([[10, 7], [3, 4]])
ts_01 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

#### Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).

In [38]:
ts_01

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
# Multiplication (known as element-wise multiplication)
ts_01 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

#### Another way: Using the TensorFlow function (where possible) 

In [40]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(ts_01, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

# Matrix mutliplication-Part 1
One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 5) @ (3, 5) won't work
* (5, 3) @ (3, 5) will work
* (3, 5) @ (5, 3) will work
The resulting matrix has the shape of the outer dimensions:
* (5, 3) @ (3, 5) -> (5, 5)
* (3, 5) @ (5, 3) -> (3, 3)

🔑 Note: '@' in Python is the symbol for matrix multiplication.



In [41]:
# Matrix multiplication in TensorFlow
print(ts_01)
tf.matmul(ts_01, ts_01)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [42]:
# Matrix multiplication with Python operator '@'
ts_01 @ ts_01


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
ts_01 * ts_01

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [44]:
import numpy as np
np_01 = np.array([[1,2,3],[4,5,6]])
np_01.shape

(2, 3)

In [45]:
np_01

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.vstack([np_01,[4,44,444]])

array([[  1,   2,   3],
       [  4,   5,   6],
       [  4,  44, 444]])

In [47]:
batch = [ [[2, 2],
           [2, 2]],
          [[3, 3],
           [3, 3]],
          [[4, 4],
           [4, 4]] ] 
t = tf.convert_to_tensor(batch, dtype=np.float32)
row_to_add = [1,1]         
appended_t = tf.map_fn(lambda x: tf.concat((x, [row_to_add]), axis=0), t)
appended_t

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[2., 2.],
        [2., 2.],
        [1., 1.]],

       [[3., 3.],
        [3., 3.],
        [1., 1.]],

       [[4., 4.],
        [4., 4.],
        [1., 1.]]], dtype=float32)>

# Matrix Mutliplication-Part 1
Let's try tf.reshape() first.

In [48]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(appended_t, shape=(3,2, 3))

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[2., 2., 2.],
        [2., 1., 1.]],

       [[3., 3., 3.],
        [3., 1., 1.]],

       [[4., 4., 4.],
        [4., 1., 1.]]], dtype=float32)>

In [49]:
appended_t

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[2., 2.],
        [2., 2.],
        [1., 1.]],

       [[3., 3.],
        [3., 3.],
        [1., 1.]],

       [[4., 4.],
        [4., 4.],
        [1., 1.]]], dtype=float32)>

In [50]:
ts_03 = tf.Variable([[2,3,4],
                     [5,6,7]])
ts_04 = tf.Variable([[7,8,9],
                     [5,60,7]])
ts_03.shape, ts_04.shape

(TensorShape([2, 3]), TensorShape([2, 3]))

In [51]:
# Try matrix multiplication with reshaped Y
ts_03 @ tf.reshape(ts_04, shape=(3, 2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[281,  59],
       [509, 119]], dtype=int32)>

It worked, let's try the same with a reshaped X, except this time we'll use tf.transpose() and tf.matmul().

# Matrix Multiplication_Part 2

In [52]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(ts_03)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 6],
       [4, 7]], dtype=int32)>

In [53]:
ts_03

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

In [54]:
# Try matrix multiplication 
tf.matmul(tf.transpose(ts_03), ts_04)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39, 316,  53],
       [ 51, 384,  69],
       [ 63, 452,  85]], dtype=int32)>

In [55]:
# You can achieve the same result with parameters
tf.matmul(a=ts_03, b=ts_04, transpose_a=True, transpose_b=False)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39, 316,  53],
       [ 51, 384,  69],
       [ 63, 452,  85]], dtype=int32)>

# Matrix Multiplication_Part 3
The dot product
* `tf.matmul()`
* `tf.tensordot()`

In [56]:
print(f'dot product when axes=0: {tf.tensordot(tf.constant([1,2,3]), tf.constant((4,5,6)), axes=0).numpy()}') 

print(f'dot product when axes=1: {tf.tensordot(tf.constant([1,2,3]), tf.constant((4,5,6)), axes=1).numpy()}') 

dot product when axes=0: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
dot product when axes=1: 32


In [57]:
print(tf.tensordot(ts_03,ts_04, axes=0))
print(ts_03)
print(ts_04)

tf.Tensor(
[[[[ 14  16  18]
   [ 10 120  14]]

  [[ 21  24  27]
   [ 15 180  21]]

  [[ 28  32  36]
   [ 20 240  28]]]


 [[[ 35  40  45]
   [ 25 300  35]]

  [[ 42  48  54]
   [ 30 360  42]]

  [[ 49  56  63]
   [ 35 420  49]]]], shape=(2, 3, 2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  8,  9],
       [ 5, 60,  7]], dtype=int32)>


In [58]:
print(f'dot product when axes=0: {tf.tensordot(tf.constant([1,2]), tf.constant((4,5,6)), axes=0).numpy()}') 


dot product when axes=0: [[ 4  5  6]
 [ 8 10 12]]


# Changing the datatype of a tensor
tf.cast()


In [59]:
ts_05 = tf.constant([1.9,3])
ts_05.dtype

tf.float32

In [60]:
tf.cast(ts_05, dtype=tf.int16)

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 3], dtype=int16)>

In [61]:
# Change from int32 to float32
C = tf.constant([1, 7])
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [62]:
# Create tensor with negative values
# Getting the absolute value¶

D = tf.constant([-7, -10])
D = tf.abs(D)
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [63]:
# Finding the min, max, mean, sum (aggregation)¶

###Sum

In [64]:
print(tf.reduce_sum(ts_04, axis=0).numpy())
print(tf.reduce_sum(ts_04, axis=1).numpy())
print(tf.reduce_sum(ts_04).numpy())

[12 68 16]
[24 72]
96


#### Mean

In [65]:
print(tf.reduce_mean(ts_04, axis=0).numpy())
print(tf.reduce_mean(ts_04, axis=1).numpy())
print(tf.reduce_mean(ts_04).numpy())

[ 6 34  8]
[ 8 24]
16


# Standard Deviation of A Tensor
the tesnor should be float type

In [66]:
ts_04 = tf.cast(ts_04,dtype=tf.float16)
print(tf.math.reduce_std(ts_04, axis=0).numpy())
print(tf.math.reduce_std(ts_04, axis=1).numpy())
print(tf.math.reduce_std(ts_04).numpy())

[ 1. 26.  1.]
[ 0.8164 25.47  ]
19.72


In [67]:
x1 = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_std(x1).numpy()

1.118034

In [68]:
import tensorflow_probability as tfp
print(tfp.stats.stddev(ts_04,sample_axis=1).numpy())
# print(tf.reduce_mean(ts_04, axis=1).numpy())
# print(tf.reduce_mean(ts_04).numpy())

[ 0.8164 25.47  ]


In [69]:
ts_04

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[ 7.,  8.,  9.],
       [ 5., 60.,  7.]], dtype=float16)>

# Finding the Positional Maximum and Minimum of a Tensor

In [70]:
tf.random.set_seed(42)
ts_06 = tf.random.uniform([2,2,50])
ts_06

<tf.Tensor: shape=(2, 2, 50), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
         0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
         0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
        [0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
         0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
         0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
         0.18282163, 0.13179815, 0.64636123, 0.955

In [71]:
tf.argmax(ts_06, axis=2)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[42,  2],
       [48,  9]])>

In [72]:
tf.reduce_max(ts_06, axis=1)

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[0.6645621 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
        0.82577336, 0.74011743, 0.8724445 , 0.7588748 , 0.3380444 ,
        0.3103881 , 0.7223358 , 0.60670924, 0.7498598 , 0.5746088 ,
        0.8996835 , 0.13179815, 0.64636123, 0.9559475 , 0.6670735 ,
        0.72942245, 0.54583454, 0.44735897, 0.6767061 , 0.6602763 ,
        0.7052754 , 0.898633  , 0.31386292, 0.8527372 , 0.96815526,
        0.9485276 , 0.29590535, 0.9356605 , 0.5263394 , 0.494308  ,
        0.262277  , 0.8457197 , 0.90045524, 0.6409379 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.84361756, 0.9355587 , 0.16461694, 0.7381023 , 0.6247839 ],
       [0.8245703 , 0.5139042 , 0.92604184, 0.8398135 , 0.31875753,
        0.22090447, 0.79542184, 0.75567424, 0.92142665, 0.9348017 ,
        0.60455227, 0.47940433, 0.4355166 , 0.52324045, 0.92557526,
        0.8645121 , 0.636765  , 0.8498118 , 0.35401833, 0.7576997 

In [73]:
F = ts_06[0,0]
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 42
The maximum value of F is: 0.967138409614563
Using tf.argmax() to index F, the maximum value of F is: 0.967138409614563
Are the two max values the same (they should be)? True


# Squeezing a Tensor
Remove the dimension of size 1 from the shape of the tensor

In [74]:
ts_06[0][0]

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
ts_07 = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
ts_07.shape, ts_07.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [76]:
ts_07

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[50, 51, 72, 25, 41, 25,  8, 91, 56, 46, 32, 81, 30, 23, 96,
           53, 36, 92, 79, 51, 12, 65,  5, 69, 29, 20, 11, 71, 60, 76,
           14, 36,  1, 33, 78, 83, 32, 84, 48, 91, 20, 88,  2, 59, 29,
           73, 47, 73, 37,  0]]]]])>

In [77]:
ts_08 = tf.squeeze(ts_07)
ts_08

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([50, 51, 72, 25, 41, 25,  8, 91, 56, 46, 32, 81, 30, 23, 96, 53, 36,
       92, 79, 51, 12, 65,  5, 69, 29, 20, 11, 71, 60, 76, 14, 36,  1, 33,
       78, 83, 32, 84, 48, 91, 20, 88,  2, 59, 29, 73, 47, 73, 37,  0])>

In [78]:
ts_08.ndim

1

In [79]:
ts_07.shape, ts_08.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

# One-Hot Encodig Tensors

In [80]:
ts_02 = tf.Variable([1,2,3,4])
tf.one_hot(ts_02, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [81]:
tf.one_hot([1,5,4], depth=6)

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)>

# Squaring, log, square root

In [82]:
# Create a new tensor
ts_08 = tf.constant(np.arange(1, 10))

ts_09 = tf.square(ts_08)
print(ts_08.numpy())
print(ts_09.numpy())

[1 2 3 4 5 6 7 8 9]
[ 1  4  9 16 25 36 49 64 81]


In [83]:
# Find the squareroot - needs to be non-integer
tf.sqrt(tf.cast(ts_08, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [84]:
tf.math.log(tf.cast(ts_08, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Manipulating tf.Variable tensors

Tensors created with tf.Variable() can be changed in place using methods such as:

.assign() - assign a different value to a particular index of a variable tensor.
.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [85]:
ts_10 = tf.Variable(np.arange(0, 5))
ts_10

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [86]:
# Assign the final value a new value of 50
ts_10.assign([0, 1, 2,  50,4])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2, 50,  4])>

In [87]:
ts_10.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 60, 14])>

# Tensors and NumPy
By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

In [88]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Using @tf.function
In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function.
In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [89]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [90]:
# Create the same function and decorate it with tf.function
@tf.function
def function(x, y):
  return x ** 2 + y

function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# Finding access to GPUs
We've mentioned GPUs plenty of times throughout this notebook.

So how do you check if you've got one available?

You can check if you've got access to a GPU using tf.config.list_physical_devices().

In [91]:
print(tf.config.list_physical_devices('GPU'))

[]


If the above outputs an empty array (or nothing), it means you don't have access to a GPU (or at least TensorFlow can't find it).

If you're running in Google Colab, you can access a GPU by going to Runtime -> Change Runtime Type -> Select GPU (note: after doing this your notebook will restart and any variables you've saved will be lost).

You can also find information about your GPU using !nvidia-smi.

In [92]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



🔑 Note: If you have access to a GPU, TensorFlow will automatically use it whenever possible.